//
//  PhotosPresenter.swift
//  TestTask_DownloadPictures
//
//  Created by Кирилл Нескоромный on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotosPresentationLogic
{
  func presentSomething(response: Photos.Something.Response)
}

class PhotosPresenter: PhotosPresentationLogic
{
  weak var viewController: PhotosDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Photos.Something.Response)
  {
    let viewModel = Photos.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
