//
//  PhotosInteractor.swift
//  TestTask_DownloadPictures
//
//  Created by Кирилл Нескоромный on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotosBusinessLogic {
  func doSomething(request: Photos.ShowPhotos.Request)
}

protocol PhotosDataStore {
  var name: String { get set }
}

class PhotosInteractor: PhotosBusinessLogic, PhotosDataStore {
  var presenter: PhotosPresentationLogic?
  var worker: PhotosWorker?
  var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Photos.ShowPhotos.Request) {
    worker = PhotosWorker()
    worker?.doSomeWork()
    
    let response = Photos.ShowPhotos.Response(name: name)
    presenter?.presentPhotos(response: response)
  }
}
