//
//  PhotosRouter.swift
//  TestTask_DownloadPictures
//
//  Created by Кирилл Нескоромный on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PhotosRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol PhotosDataPassing {
    var dataStore: PhotosDataStore? { get }
}

class PhotosRouter: NSObject, PhotosRoutingLogic, PhotosDataPassing {
    
    weak var viewController: PhotosViewController?
    var dataStore: PhotosDataStore?
}
