//
//  PhotosPresenter.swift
//  TestTask_DownloadPictures
//
//  Created by Кирилл Нескоромный on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol PhotosPresentationLogic {
    func presentPhotos(response: Photos.ShowPhotos.Response)
}

class PhotosPresenter: PhotosPresentationLogic {
    
    weak var viewController: PhotosDisplayLogic?
    
    func presentPhotos(response: Photos.ShowPhotos.Response) {
        
        var rows = [PhotoCellViewModel]()
        
        response.photos.forEach { photo in
            
            let photo = PhotoCellViewModel(photo: photo)
            rows.append(photo)
        }
        let viewModel = Photos.ShowPhotos.ViewModel(name: response.name,
                                                    rows: rows)
        viewController?.displayPhotos(viewModel: viewModel)
    }
}
