//
//  PhotosInteractor.swift
//  TestTask_DownloadPictures
//
//  Created by Кирилл Нескоромный on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol PhotosBusinessLogic {
    func passData()
}

protocol PhotosDataStore {
    var name: String { get set }
    var photos: [Photo] { get set }
    
}

class PhotosInteractor: PhotosBusinessLogic, PhotosDataStore {
    
    var presenter: PhotosPresentationLogic?
    
    var name: String = ""
    var photos: [Photo] = []
    
    func passData() {
        let response = Photos.ShowPhotos.Response(name: name, photos: photos)
        presenter?.presentPhotos(response: response)
    }
}
