//
//  UserListInteractor.swift
//  TestTask_DownloadPictures
//
//  Created by Кирилл Нескоромный on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserListBusinessLogic {
    func fetchUsers()
}

protocol UserListDataStore {
    var users: [User] { get }
}

class UserListInteractor: UserListBusinessLogic, UserListDataStore {
    
    var presenter: UserListPresentationLogic?
    var users = [User]()
    
    func fetchUsers() {
        NetworkManager.shared.fetchData(
            strURL: URLStrings.users.rawValue
        ) { [weak self] users in
            
            self?.users = users
            let response = UserList.ShowUsers.Response(users: users)
            self?.presenter?.presentUsers(response: response)
        }
    }
    
}
