//
//  UserListModels.swift
//  TestTask_DownloadPictures
//
//  Created by Кирилл Нескоромный on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
typealias UserCellViewModel = UserList.ShowUsers.ViewModel.UserCellViewModel

protocol CellIdentifiable {
    var identifier: String { get }
}

enum UserList {
  // MARK: Use cases
  
  enum ShowUsers {
    // интерактор - презентер
    struct Response {
        let users: [User]
    }
      // презентер - контроллер
    struct ViewModel {
        struct UserCellViewModel: CellIdentifiable {
            let name: String
            var identifier: String {
                "UserCell"
            }
            
            init(user: User) {
                name = user.name
            }
        }
        let rows: [UserCellViewModel]
    }
  }
}
