//
//  UserListPresenter.swift
//  TestTask_DownloadPictures
//
//  Created by Кирилл Нескоромный on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserListPresentationLogic
{
  func presentSomething(response: UserList.Something.Response)
}

class UserListPresenter: UserListPresentationLogic
{
  weak var viewController: UserListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: UserList.Something.Response)
  {
    let viewModel = UserList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
