//
//  UserListInteractor.swift
//  TestTask_DownloadPictures
//
//  Created by Кирилл Нескоромный on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

//import UIKit

protocol UserListBusinessLogic {
    func fetchUsers()
    func fetchAlbums()
    func fetchPhotos()
}

protocol UserListDataStore {
    var users: [User] { get }
    var albums: [Album] { get }
    var photos: [Photo] { get }
    
}

class UserListInteractor: UserListBusinessLogic, UserListDataStore {
    
    var presenter: UserListPresentationLogic?
    
    var users = [User]()
    var albums = [Album]()
    var photos = [Photo]()
    
    func fetchUsers() {
        NetworkManager.shared.fetchData(
            strURL: URLStrings.users.rawValue,
            type: [User].self
        ) { [weak self] users in
            
            self?.users = users
            let response = UserList.ShowUsers.Response(users: users)
            self?.presenter?.presentUsers(response: response)
        }
    }
    func fetchAlbums() {
        NetworkManager.shared.fetchData(
            strURL: URLStrings.albums.rawValue,
            type: [Album].self)
        { [weak self] albums in
            
            self?.albums = albums
        }
    }
    func fetchPhotos() {
        NetworkManager.shared.fetchData(
            strURL: URLStrings.photos.rawValue,
            type: [Photo].self)
        { [weak self] photos in
            
            self?.photos = photos
        }
    }
}
